db:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=my-secret-pw
web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/src
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    - ENVIRONMENT=development
    - DB_HOST=db
    - DB_PORT=3306
    - DB_USER=root
    - DB_PASSWORD=my-secret-pw
    - DB_DATABASE=redmine_dev
    - AIRBRAKE_API_KEY=
    - SECRET_KEY=a2bbb1fb6ce1d7979b25b967469f4617aba4b445c65cf0be153e5b848a5cd80469b9a630ab2fc267
    - SMTP_HOST=localhost
    - SMTP_PORT=25
    - SMTP_USER=nouser
    - SMTP_PASSWORD=nopw
