mysql: &mysql
  adapter: mysql2
  database: "<%=ENV["DB_DATABASE"]%>"
  username: "<%=ENV["DB_USERNAME"]%>"
  password: "<%=ENV["DB_PASSWORD"]%>"
  host:     <%=ENV["DB_HOST"]%>
  port:     <%=ENV["DB_PORT"]%>

defaults: &defaults
  pool: 5
  timeout: 5000
  encoding: utf8
  <<: *<%= ENV['RAILS_DB'] || "mysql" %>

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
